version: '3.3'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    volumes:
      - "./docker_db/mysql/database_prod.sql:/docker-entrypoint-initdb.d/0_init\
        .sql"
    environment:
      MYSQL_DATABASE: mediscreendb
      MYSQL_USER: mediuser
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - web-server
    restart: always

  patient:
    image: patient
    container_name: patient
    build:
      context: ./patient/
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/mediscreendb?serverTimezone=Europe/Paris
      - SPRING_DATASOURCE_USERNAME=mediuser
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - web-server
    depends_on:
      - mysql_db
    restart: always

  ui:
    image: ui
    container_name: ui
    build:
      context: ./ui/
      dockerfile: Dockerfile
    environment:
      - PROXY_PATIENT=http://patient:8081/patient
      - PROXY_NOTE=http://note:8082/note
      - PROXY_ASSESS=assess:8083/assess
    ports:
      - 8080:8080
    networks:
      - web-server
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./docker_db/mongodb/mongod.conf:/etc/mongod.conf
      - ./docker_db/mongodb/data/db/:/data/db/
    networks:
      - web-server
    restart: always

  patientHistory:
    image: note
    container_name: note
    build:
      context: ./patientHistory/
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
    ports:
      - 8082:8082
    networks:
      - web-server
    depends_on:
      - mongodb
    restart: always

patientAssessment:
  image: assess
  container_name: assess
  build:
    context: ./patientAssessment/
    dockerfile: Dockerfile
  environment:
    - PROXY_PATIENT=patient:8081/patient
    - PROXY_NOTE=note:8082/note
  ports:
    - 8083:8083
  networks:
    - web-server
  restart: always

networks:
  web-server:
    driver: bridge
