package com.patientHistory.model;

import java.time.LocalDate;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * The Class Note.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "notes") // Maps Entity class objects to JSON formatted Documents
public class Note {

    /** The id. */
    @Id		// making this variable as ID, will be auto-generated by MongoDB
    private String id;

    /** The patient id. */
    @Field(value = "patient_id")
    private Integer patientId;

    /** The date. */
    private LocalDate date;

    /** The note. */
    private String note;



  	// *******************************************************************



    /**
	   * Instantiates a new note.
	   *
	   * @param patientId the patient id
	   * @param date the date
	   * @param note the note
	   */
	  public Note(
    		final Integer patientId,
    		final LocalDate date,
    		final String note) {
        this.patientId = patientId;
        this.date = date;
        this.note = note;
    }


  	// *******************************************************************



}